CREATE TABLE Singer (
	ID INTEGER IDENTITY (1, 1) NOT NULL,
	Name VARCHAR (18) NOT NULL PRIMARY KEY,
	Sex VARCHAR (6) NULL,
	PinYin VARCHAR (12) NULL,
	[Visible] SMALLINT NOT NULL DEFAULT 1,
	Num INTEGER NULL,
	HavePhoto SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE System (
	Code VARCHAR (8) NOT NULL PRIMARY KEY,
	Name VARCHAR (50) NOT NULL,
	Version VARCHAR (10) NULL,
	Charset SMALLINT NULL DEFAULT 134,
	Language VARCHAR (8) NULL,
	Class VARCHAR (8) NULL,
	Singer1 VARCHAR (18) NULL,
	Singer2 VARCHAR (18) NULL,
	Singer3 VARCHAR (18) NULL,
	Singer4 VARCHAR (18) NULL,
	Num INTEGER NULL,
	Pinyin VARCHAR (10) NULL,
	WBH VARCHAR (10) NULL,
	PlayNum INTEGER NULL DEFAULT 0,
	Klok VARCHAR (1) NOT NULL DEFAULT 0,
	Sound VARCHAR (1) NOT NULL DEFAULT 1,
	FileSize INTEGER NULL,
	InputDate timestamp NULL,
	isNewSong SMALLINT NOT NULL DEFAULT 1,
	VolumeK INTEGER DEFAULT 0,
	VolumeS INTEGER DEFAULT 0,
	SoundMode INTEGER DEFAULT 0,
	HaveSong INTEGER DEFAULT 0,
	VideoType VARCHAR(5) DEFAULT 'DIVX',
	DefaultTag INTEGER DEFAULT 0,
	Quality SMALLINT NOT NULL DEFAULT 0,
	Password INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE ServerIndex (
	DiskName VARCHAR (50) NULL,
	Code VARCHAR (8) NULL,
	Path VARCHAR (100) NULL,
	ExtName VARCHAR (3) NULL,
	FileSize INTEGER
);
CREATE TABLE UpdateIndex (
	IndexTag INTEGER
);
CREATE TRIGGER trig1 DELETE ON system
BEGIN
	UPDATE UpdateIndex SET IndexTag=1;
END;
CREATE TRIGGER trig3 INSERT ON system
BEGIN
	UPDATE UpdateIndex SET IndexTag=1;
END;
CREATE TRIGGER trig4 DELETE ON singer
BEGIN
	UPDATE UpdateIndex SET IndexTag=1;
END;
CREATE TRIGGER trig6 INSERT ON singer
BEGIN
	UPDATE UpdateIndex SET IndexTag=1;
END;

