LIB=libktv.a 

SUBDIRS = tinyxml avio

SRC = \
    ini.c           \
    osnet.c         \
    selected.c      \
    strext.c        \
    crypt/aes.c     \
    crypt/base64.c  \
    crypt/des.c     \
    crypt/hd.c      \
    crypt/md5.c     \
    vstp/url.c      \
    vstp/vstp.c

CLEANFILE+=libktv.a libtinyxml.a libnetio

-include ../inc.Makefile
