#!/bin/bash
#
#

modprobe usb-storage

umount /dev/sda1 2>/dev/null
umount /dev/sdb1 2>/dev/null
umount /dev/sdc1 2>/dev/null
umount /dev/sdd1 2>/dev/null

for i in 0 1 2 3; do
	USBDEV="/proc/scsi/usb-storage-${i}/${i}"
	if [ -f ${USBDEV} ]; then
		grep "Attached: Yes" ${USBDEV} >/dev/null
		if [ $? -eq 0 ]; then
			case $i in
			0) mount /dev/sda1 /mnt/usb 
			  ;;
			1) mount /dev/sdb1 /mnt/usb
			  ;;
			2) mount /dev/sdc1 /mnt/usb
			  ;;
			3) mount /dev/sdd1 /mnt/usb
			  ;;
			esac
#			echo "Start Add New Song" | send
			addsong /mnt/usb /ktvdata/song2000.db /tmp/disk.ini
			umount /mnt/usb
			song -l -u
			poweroff
		fi
	fi
done

